### PR TITLE
Export 2018 09 28

### PR DESCRIPTION
**Pull request by severinrudie**

### CODE REVIEW

**Comment by flodolo** [comment]
You made this pull request from an [obsolete fork](https://github.com/Baron-Severin/firefoxtv-l10n)

>  Pull request Compare This branch is 32 commits behind mozilla-l10n:master.

**Comment by Delphine** [comment]
@Sdaswani, @bbinto: When is the l10n deadline for these strings? Are they for 3.0 release (I assume not since release candidate has already been submitted)?

Side-note, I see there are new screenshots thanks to @AaronMT. At the moment I can't seem to access them. 

Also, if these new strings are part of the 3.0 release, heads-up they are not part of the screenshots since they haven't been merged and translated yet. (and also we can't merge these new strings until they are done on the right branch)

**Comment by Sdaswani** [comment]
@mcomella will take a look tomorrow.

**Comment by mcomella** [comment]
@Baron-Severin The turbo mode strings didn't land in the repository: I don't think we should export them until they are reviewed and landed. Can this be closed?

Additionally, we haven't been following a strict sprint schedule but that should change starting this week. String exports should happen once a sprint, [on the second wednesday](https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist#string-freeze-wednesday--2), and this is not that single export.

**Comment by mcomella** [comment]
Missing context: these strings are targeted for a feature for the v3.1 release.

**Comment by Sdaswani** [comment]
Cool @Delphine - so hopefully the current set of screenshots is all you need to sign off on locales for 3.0?

**Comment by Delphine** [comment]
@Sdaswani: Correct! Let me know when you need that by. I think on my side tomorrow or Wed. should be good, if that works with you too.

**Comment by Sdaswani** [comment]
Tomorrow or Wednesday is fine @Delphine !

**Comment by severinrudie** [comment]
Closing until related strings are landed into master.

**Pull request closed without merging**
