### PR TITLE
Export 2018 10 16

### PR DESCRIPTION
**Pull request by severinrudie**

### CODE REVIEW

**Review by Delphine — APPROVED** [review]
LGTM! thanks :)

**Comment by Delphine** [comment]
@Baron-Severin: Could you let me know what the deadline for localizing and testing these strings are? As well as which release they are targeting?
thanks

**Comment by severinrudie** [comment]
This is targetting the v3.1 release.  We don't have a hard deadline yet, but we're hoping to have these in by the end of sprint 2 (which would be November 9th).

**Comment by Delphine** [comment]
Ok I've communicated that as a deadline for now then. Please do give a heads-up if that ever changes (especially if it's sooner ;) ). Thanks :)

**Pull request merged**
